services:
  app:
    container_name: azure_sandbox_app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: azure-sandbox-app:latest
    pull_policy: never
    command: uv run fastapi dev main.py --host 0.0.0.0
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
